---
- name: Update apt cache
  apt:
    update_cache: yes
    cache_valid_time: 3600

- name: Install nginx
  apt:
    name: "{{ nginx_package }}"
    state: present

- name: Copy nginx configuration
  template:
    src: nginx.conf.j2
    dest: /etc/nginx/nginx.conf
    validate: 'nginx -t -c %s'
  notify: reload nginx

- name: Create index.html
  template:
    src: index.html.j2
    dest: /var/www/html/index.html

- name: Start nginx
  service:
    name: nginx
    state: started
    enabled: yes
