---
- name: Setup Development Nginx
  hosts: dev_servers
  become: yes

  vars:
    nginx_workers: 1
    nginx_port: 80
    nginx_hostname: "dev.local"
    site_title: "Development Environment"
    site_color: "#FFA500"

  tasks:
    - name: Update apt cache
      apt:
        update_cache: yes
        cache_valid_time: 3600

    - name: Install nginx
      apt:
        name: nginx
        state: present

    - name: Copy nginx configuration
      template:
        src: nginx.conf.j2
        dest: /etc/nginx/nginx.conf
        validate: 'nginx -t -c %s'
      notify: reload nginx

    - name: Create index.html
      copy:
        content: |
          <!DOCTYPE html>
          <html>
          <head>
            <title>{{ site_title }}</title>
            <style>body { background: {{ site_color }}; font-family: Arial; text-align: center; padding: 50px; }</style>
          </head>
          <body>
            <h1>{{ site_title }}</h1>
            <p>Workers: {{ nginx_workers }}</p>
            <p>Port: {{ nginx_port }}</p>
          </body>
          </html>
        dest: /var/www/html/index.html

    - name: Start nginx
      service:
        name: nginx
        state: started
        enabled: yes

  handlers:
    - name: reload nginx
      service:
        name: nginx
        state: reloaded
