---
galaxy_info:
  role_name: nginx
  description: "Nginx web server for multiple environments"
  company: "HKHK"
  license: MIT
  min_ansible_version: "2.9"

  platforms:
    - name: Ubuntu
      versions:
        - jammy

  galaxy_tags:
    - web
    - nginx
    - multienv

dependencies: []
